const CAPABILITIES = Object.freeze({
  schema_revision: 9,
  server_revision: "managed-tabs-v9",
  supports_select_or_create: true,
  supports_dedicated_agent_window: true,
  supports_focus_policy: true,
  supports_focus_lease: true,
  supports_focus_restore_guard: true,
  managed_window_policy_default: "dedicated",
  managed_focus_policy_default: "background_preferred",
  supports_tabs_close: true,
  supports_tabs_get: true,
  supports_include_unscriptable_tabs: true,
  supports_wait_until_visible: true,
  supports_prune_stale: true,
  supports_finalize_task: true,
  supports_finalize_scoped_runs: true,
  list_managed_summary_only_default: true,
  managed_tab_scope_limit_default: 8,
  supports_created_agent_window_cleanup: true,
  supports_exact_agent_window_orphan_recovery: true,
  agent_window_orphan_recovery_policy: "same_browser_profile_epoch_exact_window_sole_browser_new_tab",
  supports_finalize_hint: true,
  supports_close_verification: true,
  supports_screenshot_viewport_override: true,
  screenshot_viewport_override_atomic_targets: ["viewport", "clip", "selector", "full_page"],
  supports_persistent_screenshot_viewport_override: false,
  supports_screenshot_layout_metrics: true,
  supports_design_craft_l4_evidence_manifest: true,
  supports_durable_jobs: true,
  supports_job_restart_recovery: true,
  supports_job_abort: false,
  supports_persistent_debugger: false,
  supports_bounded_console_observation: true,
  debugger_commands_serialized_per_tab: true,
  debugger_ui_scope: "browser_profile",
  debugger_profile_isolation_requires_separate_browser_instance: true,
  supports_protocol_solver_apply: false,
  managed_registry_default_path: "~/.browser67/tab-workspace/managed-tabs.json",
  legacy_managed_registry_path: "~/.tmwd-browser-mcp/tab-workspace/managed-tabs.json",
});

export {
  CAPABILITIES,
};
