import { NATIVE_INPUT_MAX_TIMEOUT_MS } from "../native/input.mjs";

const BROWSER_CORE_TOOL_SCHEMAS = {
  browser_scan: {
    description: "GA-style web_scan: tabs + simplified content from active tab. Direct MCP default is auto; core web_scan defaults to TMWD user browser.",
    inputSchema: {
      type: "object",
      properties: {
        tabs_only: { type: "boolean", default: false },
        tab_id: { type: "string" },
        switch_tab_id: { type: "string" },
        session_id: { type: "string" },
        workspace_key: { type: "string" },
        task_id: { type: "string" },
        session_url_pattern: { type: "string" },
        tmwd_mode: { type: "string", enum: ["auto", "tmwd", "remote_cdp", "cdp"], default: "auto" },
        tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
        tmwd_ws_endpoint: { type: "string" },
        tmwd_link_endpoint: { type: "string" },
        text_only: { type: "boolean", default: false },
        main_only: { type: "boolean", default: false },
        main_only_fallback_to_full: { type: "boolean", default: true },
        main_only_min_chars: { type: "number", minimum: 100, maximum: 10_000 },
        main_only_min_coverage: { type: "number", minimum: 0.05, maximum: 0.95 },
        max_chars: { type: "number", minimum: 1_000, maximum: 300_000 },
        timeout_ms: { type: "number", minimum: 100, maximum: 120_000 },
        cdp_endpoint: { type: "string" },
      },
    },
  },
  browser_execute_js: {
    description: "GA-style web_execute_js via TMWD bridge commands (cmd=tabs/cookies/cdp/batch) or plain JS. Likely click/popup scripts use bounded new-target polling unless no_monitor=true. Direct MCP default is auto; core web_execute_js defaults to TMWD user browser.",
    inputSchema: {
      type: "object",
      properties: {
        script: { type: "string" },
        operation: {
          type: "string",
          enum: ["click", "focus", "set_value", "select_option", "read"],
        },
        node_ref: {
          type: "object",
          additionalProperties: false,
          properties: {
            snapshot_id: { type: "string" },
            node_id: { type: "string" },
          },
          required: ["snapshot_id", "node_id"],
        },
        expected: {
          type: "object",
          additionalProperties: false,
          properties: {
            tag: { type: "string" },
            role: { type: "string" },
            accessible_name: { type: "string" },
          },
        },
        value: { type: "string" },
        workspace_key: { type: "string" },
        task_id: { type: "string" },
        network_observation: {
          type: "object",
          additionalProperties: false,
          properties: {
            enabled: { type: "boolean", default: false },
            ttl_ms: { type: "number", minimum: 1000, maximum: 120000 },
            idle_ms: { type: "number", minimum: 50, maximum: 30000 },
            max_inflight: { type: "number", minimum: 0, maximum: 100 },
            interval_ms: { type: "number", minimum: 25, maximum: 5000 },
            ignore_patterns: {
              type: "array",
              maxItems: 100,
              items: { type: "string" },
            },
            ignore_resource_types: {
              type: "array",
              maxItems: 50,
              items: { type: "string" },
            },
          },
        },
        tab_id: { type: "string" },
        switch_tab_id: { type: "string" },
        session_id: { type: "string" },
        session_url_pattern: { type: "string" },
        tmwd_mode: { type: "string", enum: ["auto", "tmwd", "remote_cdp", "cdp"], default: "auto" },
        tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
        tmwd_ws_endpoint: { type: "string" },
        tmwd_link_endpoint: { type: "string" },
        no_monitor: { type: "boolean", default: false },
        new_tab_wait_ms: { type: "number", minimum: 0, maximum: 5_000 },
        native_auto_fallback: { type: "boolean", default: false },
        native_auto_fallback_policy: {
          type: "string",
          enum: ["strict", "balanced", "aggressive"],
          default: "balanced",
        },
        native_auto_execute: { type: "boolean", default: false },
        native_execute_action_scope: {
          type: "string",
          enum: ["non_pointer", "all"],
          default: "non_pointer",
        },
        native_fallback_action: {
          type: "string",
          enum: [
            "activate_window",
            "move",
            "click",
            "double_click",
            "press",
            "type",
            "paste",
            "scroll",
            "get_window_rect",
          ],
        },
        native_fallback_args: { type: "object" },
        native_fallback_timeout_ms: { type: "number", minimum: 500, maximum: NATIVE_INPUT_MAX_TIMEOUT_MS },
        timeout_ms: { type: "number", minimum: 100, maximum: 120_000 },
        output_mode: { type: "string", enum: ["full", "compact"], default: "full" },
        max_return_chars: { type: "number", minimum: 200, maximum: 300_000 },
        cdp_endpoint: { type: "string" },
        target_url_contains: { type: "string" },
      },
    },
  },
  browser_wait: {
    description: "Wait for selector/text/function/DOM-stable/network-idle conditions in the selected TMWD or CDP tab.",
    inputSchema: {
      type: "object",
      properties: {
        type: {
          type: "string",
          enum: ["selector", "text", "function", "dom_stable", "resource_quiet", "network_idle"],
          default: "selector",
        },
        selector: { type: "string" },
        text: { type: "string" },
        predicate: { type: "string" },
        code: { type: "string" },
        visible: { type: "boolean", default: true },
        stable_ms: { type: "number", minimum: 50, maximum: 30_000 },
        idle_ms: { type: "number", minimum: 50, maximum: 30_000 },
        max_inflight: { type: "number", minimum: 0, maximum: 100 },
        ignore_patterns: {
          type: "array",
          maxItems: 100,
          items: { type: "string" },
        },
        ignore_resource_types: {
          type: "array",
          maxItems: 50,
          items: { type: "string" },
        },
        root_selector: { type: "string" },
        ignore_selectors: {
          type: "array",
          maxItems: 100,
          items: { type: "string" },
        },
        ignore_attributes: {
          type: "array",
          maxItems: 100,
          items: { type: "string" },
        },
        mutation_threshold: { type: "number", minimum: 0, maximum: 10_000 },
        interval_ms: { type: "number", minimum: 25, maximum: 5_000 },
        timeout_ms: { type: "number", minimum: 100, maximum: 120_000 },
        tab_id: { type: "string" },
        switch_tab_id: { type: "string" },
        session_id: { type: "string" },
        workspace_key: { type: "string" },
        task_id: { type: "string" },
        session_url_pattern: { type: "string" },
        tmwd_mode: { type: "string", enum: ["auto", "tmwd", "remote_cdp", "cdp"], default: "auto" },
        tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
        tmwd_ws_endpoint: { type: "string" },
        tmwd_link_endpoint: { type: "string" },
        cdp_endpoint: { type: "string" },
      },
    },
  },
  browser_transport_health: {
    description: "Probe TMWD ws/link transport health and return actionable readiness diagnostics.",
    inputSchema: {
      type: "object",
      properties: {
        tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
        tmwd_ws_endpoint: { type: "string" },
        tmwd_link_endpoint: { type: "string" },
        session_id: { type: "string" },
        session_url_pattern: { type: "string" },
        include_target_metadata: {
          type: "boolean",
          default: false,
          description: "Opt in to selected tab id and URL in successful health results.",
        },
        timeout_ms: { type: "number", minimum: 100, maximum: 10_000 },
      },
    },
  },
  browser_run_ops: {
    description: "Create and manage externalized browser task run records; inspect provides read-only aggregate runtime inventory.",
    inputSchema: {
      type: "object",
      properties: {
        action: {
          type: "string",
          enum: ["prepare", "status", "record_event", "finish", "list", "inspect"],
          default: "status",
        },
        run_id: { type: "string" },
        workspace_key: { type: "string" },
        task_id: { type: "string" },
        group: { type: "string" },
        title: { type: "string" },
        event: { type: "string" },
        status: { type: "string" },
        data: { type: "object" },
        evidence: { type: "object" },
        summary_only: { type: "boolean", default: false },
        include_storage: {
          type: "boolean",
          default: false,
          description: "For inspect only, recursively aggregate recognized run storage bytes.",
        },
        stale_running_after_minutes: {
          type: "number",
          minimum: 1,
          maximum: 10_080,
          default: 120,
        },
        max_items: { type: "number", minimum: 1, maximum: 500 },
      },
    },
  },
  browser_job_ops: {
    description: "Start, inspect, fetch, persist, and recover run-backed browser execution jobs. Set no_monitor=false to enable bounded new-target polling. Cancellation is explicit intent-only once Runtime.evaluate is in flight.",
    inputSchema: {
      type: "object",
      properties: {
        action: {
          type: "string",
          enum: ["start", "status", "result", "cancel", "list"],
          default: "status",
        },
        job_id: { type: "string" },
        title: { type: "string" },
        workspace_key: { type: "string" },
        task_id: { type: "string" },
        run_id: { type: "string" },
        prepare_run: { type: "boolean", default: true },
        summary_only: { type: "boolean", default: false },
        max_items: { type: "number", minimum: 1, maximum: 500 },
        script: { type: "string" },
        tab_id: { type: "string" },
        switch_tab_id: { type: "string" },
        session_id: { type: "string" },
        session_url_pattern: { type: "string" },
        tmwd_mode: { type: "string", enum: ["auto", "tmwd", "remote_cdp", "cdp"], default: "auto" },
        tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
        tmwd_ws_endpoint: { type: "string" },
        tmwd_link_endpoint: { type: "string" },
        no_monitor: { type: "boolean", default: true },
        new_tab_wait_ms: { type: "number", minimum: 0, maximum: 5_000 },
        native_auto_fallback: { type: "boolean", default: false },
        native_auto_fallback_policy: {
          type: "string",
          enum: ["strict", "balanced", "aggressive"],
          default: "balanced",
        },
        native_auto_execute: { type: "boolean", default: false },
        native_execute_action_scope: {
          type: "string",
          enum: ["non_pointer", "all"],
          default: "non_pointer",
        },
        native_fallback_action: {
          type: "string",
          enum: [
            "activate_window",
            "move",
            "click",
            "double_click",
            "press",
            "type",
            "paste",
            "scroll",
            "get_window_rect",
          ],
        },
        native_fallback_args: { type: "object" },
        native_fallback_timeout_ms: { type: "number", minimum: 500, maximum: NATIVE_INPUT_MAX_TIMEOUT_MS },
        timeout_ms: { type: "number", minimum: 100, maximum: 120_000 },
        output_mode: { type: "string", enum: ["full", "compact"], default: "compact" },
        max_return_chars: { type: "number", minimum: 200, maximum: 300_000 },
        cdp_endpoint: { type: "string" },
        target_url_contains: { type: "string" },
      },
    },
  },
  browser_extract: {
    description: "Capture actionable-snapshot.v2 from the active managed document for reliable follow-up NodeRef operations.",
    inputSchema: {
      type: "object",
      properties: {
        selector_limit: { type: "number", minimum: 1, maximum: 5000 },
        tmwd_mode: { type: "string", enum: ["auto", "tmwd", "remote_cdp", "cdp"], default: "auto" },
        tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
        tmwd_ws_endpoint: { type: "string" },
        tmwd_link_endpoint: { type: "string" },
        cdp_endpoint: { type: "string" },
        workspace_key: { type: "string" },
        task_id: { type: "string" },
        timeout_ms: { type: "number", minimum: 100, maximum: 120_000 },
        switch_tab_id: { type: "string" },
        tab_id: { type: "string" },
        session_id: { type: "string" },
        session_url_pattern: { type: "string" },
      },
    },
  },
  browser_diff: {
    description: "Compare two actionable snapshot references and return semantic-diff.v2 state changes.",
    inputSchema: {
      type: "object",
      properties: {
        before_snapshot_id: { type: "string" },
        after_snapshot_id: { type: "string" },
        capture_after: { type: "boolean", default: false },
        workspace_key: { type: "string" },
        task_id: { type: "string" },
        tab_id: { type: "string" },
        switch_tab_id: { type: "string" },
        session_id: { type: "string" },
        tmwd_mode: { type: "string", enum: ["auto", "tmwd", "remote_cdp", "cdp"], default: "auto" },
        tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
        tmwd_ws_endpoint: { type: "string" },
        tmwd_link_endpoint: { type: "string" },
        cdp_endpoint: { type: "string" },
      },
      required: ["before_snapshot_id"],
    },
  },
  browser_tab_ops: {
    description: "Tab/session operations over the selected browser route (TMWD user browser or explicit remote-debugging CDP).",
    inputSchema: {
      type: "object",
      properties: {
        op: {
          type: "string",
          enum: ["list", "switch", "current", "list_sessions", "find_session", "set_session", "current_session"],
        },
        tab_id: { type: "string" },
        session_id: { type: "string" },
        url_pattern: { type: "string" },
        include_disconnected: { type: "boolean", default: false },
        include_unscriptable: { type: "boolean", default: false },
        include_internal: { type: "boolean", default: false },
        include_unmanaged: {
          type: "boolean",
          default: true,
          description: "Compatibility field. browser_tab_ops observes routable tabs and does not establish managed ownership; use browser_tab_lifecycle list_managed for ownership-filtered inventory.",
        },
        workspace_key: { type: "string" },
        task_id: { type: "string" },
        timeout_ms: { type: "number", minimum: 100, maximum: 120_000 },
        tmwd_mode: { type: "string", enum: ["auto", "tmwd", "remote_cdp", "cdp"], default: "auto" },
        tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
        tmwd_ws_endpoint: { type: "string" },
        tmwd_link_endpoint: { type: "string" },
        cdp_endpoint: { type: "string" },
      },
      required: ["op"],
    },
  },
};

export { BROWSER_CORE_TOOL_SCHEMAS };
