const IO_TOOL_SCHEMAS = {
  browser_file_ops: {
    description: "File upload helpers for real Chrome/Edge through TMWD/CDP: inspect file inputs, set local files, synthesize small in-memory files, or return a native chooser plan.",
    inputSchema: {
      type: "object",
      properties: {
        action: {
          type: "string",
          enum: ["inspect_inputs", "set_input_files", "upload_via_data_transfer", "native_file_chooser_plan"],
        },
        selector: { type: "string" },
        files: {
          type: "array",
          items: { type: "string" },
        },
        name: { type: "string" },
        filename: { type: "string" },
        content: { type: "string" },
        base64: { type: "string" },
        mime_type: { type: "string" },
        type: { type: "string" },
        tab_id: { type: "string" },
        switch_tab_id: { type: "string" },
        session_id: { type: "string" },
        session_url_pattern: { type: "string" },
        tmwd_mode: { type: "string", enum: ["auto", "tmwd", "remote_cdp", "cdp"], default: "auto" },
        tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
        tmwd_ws_endpoint: { type: "string" },
        tmwd_link_endpoint: { type: "string" },
        cdp_endpoint: { type: "string" },
        timeout_ms: { type: "number", minimum: 100, maximum: 120_000 },
      },
      required: ["action"],
    },
  },
  browser_download_ops: {
    description: "Download lifecycle helpers: allow automatic downloads, prepare a per-run token, wait for stable downloaded files, or list recent files without reading Chrome history.",
    inputSchema: {
      type: "object",
      properties: {
        action: {
          type: "string",
          enum: ["allow_automatic_downloads", "prepare", "wait", "list_recent"],
        },
        token: { type: "string" },
        download_dir: { type: "string" },
        create_dir: { type: "boolean", default: false },
        set_behavior: { type: "boolean", default: false },
        since_ms: { type: "number" },
        timeout_ms: { type: "number", minimum: 100, maximum: 120_000 },
        poll_ms: { type: "number", minimum: 100, maximum: 2_000 },
        stability_ms: { type: "number", minimum: 200, maximum: 5_000 },
        require_count: { type: "number", minimum: 1, maximum: 100 },
        pattern: { type: "string" },
        setting: { type: "string", enum: ["allow", "block", "ask"], default: "allow" },
        apply: { type: "boolean", default: true },
        dry_run: { type: "boolean", default: false },
        tab_id: { type: "string" },
        switch_tab_id: { type: "string" },
        session_id: { type: "string" },
        session_url_pattern: { type: "string" },
        tmwd_mode: { type: "string", enum: ["auto", "tmwd", "remote_cdp", "cdp"], default: "auto" },
        tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
        tmwd_ws_endpoint: { type: "string" },
        tmwd_link_endpoint: { type: "string" },
        cdp_endpoint: { type: "string" },
      },
      required: ["action"],
    },
  },
  browser_clipboard_ops: {
    description: "Minimal safe clipboard wrapper: write text or paste text without reading the user's clipboard.",
    inputSchema: {
      type: "object",
      properties: {
        action: {
          type: "string",
          enum: ["write_text", "paste_text"],
        },
        text: { type: "string" },
        selector: { type: "string" },
        real_paste: { type: "boolean", default: false },
        dry_run: { type: "boolean", default: false },
        tab_id: { type: "string" },
        switch_tab_id: { type: "string" },
        session_id: { type: "string" },
        session_url_pattern: { type: "string" },
        tmwd_mode: { type: "string", enum: ["auto", "tmwd", "remote_cdp", "cdp"], default: "auto" },
        tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
        tmwd_ws_endpoint: { type: "string" },
        tmwd_link_endpoint: { type: "string" },
        cdp_endpoint: { type: "string" },
        timeout_ms: { type: "number", minimum: 100, maximum: 120_000 },
        window_title: { type: "string" },
        window_pid: { type: "number" },
        focus_policy: {
          type: "string",
          enum: ["background_only", "background_preferred", "foreground"],
          default: "background_preferred",
        },
        focus_lease_timeout_ms: { type: "number", minimum: 1_000, maximum: 120_000 },
      },
      required: ["action"],
    },
  },
};

export { IO_TOOL_SCHEMAS };
