const VERSION = "0.5.0";

const TOOL_DEFINITIONS = {
  check_browser_health: "Verify browser67-backed browser connectivity for JS reverse tasks.",
  navigate_page: "Navigate the selected page.",
  new_page: "Create/reuse a browser67-managed page in the dedicated background Agent window by default.",
  finalize_task: "Finalize js-reverse browser67-managed pages for a workspace or task.",
  list_pages: "List TMWD-visible browser pages.",
  select_page: "Select a browser page by id.",
  list_scripts: "List script tags from the selected page.",
  get_script_source: "Read inline or external script source from the selected page.",
  search_in_scripts: "Search loaded scripts by keyword or regex.",
  find_in_script: "Find text in one script source.",
  list_network_requests: "List performance and hook-captured network requests.",
  get_network_request: "Get one captured network request by id.",
  list_websocket_connections: "List websocket activity captured by hooks or performance entries.",
  get_websocket_messages: "Get websocket messages captured by hooks.",
  get_request_initiator: "Return captured call stack for a request when hook data has it.",
  get_dom_structure: "Return a compact DOM tree snapshot.",
  list_frames: "List iframes/frames with frame paths, geometry, same-origin accessibility, and child counts.",
  detect_microfrontends: "Detect possible microfrontend runtimes, iframe/shadow/sandbox boundaries, and hook-scope limits.",
  create_hook: "Create a hook definition.",
  inject_hook: "Inject a hook definition into the selected page.",
  get_hook_data: "Read hook-captured runtime records.",
  remove_hook: "Disable a hook definition.",
  list_hooks: "List server-side hook definitions.",
  hook_function: "Shortcut for create_hook + inject_hook on a function path.",
  unhook_function: "Disable a function hook.",
  monitor_events: "Monitor DOM events in the selected page.",
  stop_monitor: "Stop DOM event monitoring.",
  trace_function: "Trace calls to a function path with hook records.",
  inject_preload_script: "Inject a runtime script now and record that early preload needs a reload-capable path.",
  set_breakpoint: "Breakpoint placeholder; hooks are preferred on this browser67-backed server.",
  set_breakpoint_on_text: "Breakpoint placeholder by text search.",
  resume: "Debugger-control placeholder.",
  pause: "Debugger-control placeholder.",
  step_over: "Debugger-control placeholder.",
  step_into: "Debugger-control placeholder.",
  step_out: "Debugger-control placeholder.",
  evaluate_on_callframe: "Debugger callframe placeholder.",
  break_on_xhr: "Install fetch/xhr hooks for a URL pattern.",
  analyze_target: "One-shot reconnaissance over DOM, scripts, network, and hook records.",
  understand_code: "Local heuristic code analysis.",
  deobfuscate_code: "Lightweight local JavaScript beautification.",
  detect_crypto: "Detect common crypto/signing primitives in code.",
  summarize_code: "Summarize code shape with local heuristics.",
  risk_panel: "Score reverse-engineering risk and next-step confidence.",
  record_reverse_evidence: "Write reverse evidence to runtime artifacts.",
  export_session_report: "Export the current js-reverse session report.",
  export_evidence_bundle: "Export a reproducible js-reverse evidence bundle with summary, network rows, hooks, redacted storage, and replay notes.",
  export_rebuild_bundle: "Export a minimal Node rebuild bundle from captured evidence.",
  diff_env_requirements: "Heuristically diff browser/local environment requirements.",
  collect_code: "Collect script code snippets matching keywords.",
  collection_diff: "Diff two code collections by content hash.",
  inject_stealth: "Inject basic anti-detection overrides into the selected page.",
  set_user_agent: "Set User-Agent override through the TMWD CDP bridge.",
  save_session_state: "Save localStorage/sessionStorage/document cookie snapshot.",
  restore_session_state: "Restore localStorage/sessionStorage snapshot.",
  get_storage: "Read document cookie, localStorage, and sessionStorage.",
  get_local_storage: "Read one localStorage key with bounded value output.",
  get_session_storage: "Read one sessionStorage key with bounded value output.",
  search_storage: "Search localStorage/sessionStorage keys and bounded value previews.",
  watch_storage_changes: "Install a non-blocking storage change watcher that records storage-change hook data.",
};

const PROPERTY_DEFINITIONS = {
  browser_instance_id: {
    type: "string",
    minLength: 1,
    maxLength: 128,
    pattern: "^[A-Za-z0-9._-]+$",
  },
  page_id: { type: "string" },
  session_id: { type: "string" },
  session_url_pattern: { type: "string" },
  url: { type: "string" },
  script_id: { type: "string" },
  source_url: { type: "string" },
  script_limit: { type: "number", minimum: 1, maximum: 500 },
  key: { type: "string" },
  keywords: {
    type: "string",
    description: "Pipe-separated keywords, for example: sign|token|crypto.",
  },
  pattern: { type: "string" },
  request_id: { type: "string" },
  hook_id: { type: "string" },
  monitor_id: { type: "string" },
  type: { type: "string" },
  target: { type: "string" },
  code: { type: "string" },
  events: { type: "array", items: { type: "string" } },
  view: { type: "string", enum: ["summary", "raw"] },
  max_records: { type: "number", minimum: 1, maximum: 1000 },
  max_value_chars: { type: "number", minimum: 0, maximum: 20000 },
  include_values: { type: "boolean", default: false },
  storage_area: { type: "string", enum: ["both", "localStorage", "sessionStorage"], default: "both" },
  watch_id: { type: "string" },
  channel: { type: "string" },
  task_id: { type: "string" },
  taskId: { type: "string", description: "Compatibility alias for task_id." },
  workspace_key: { type: "string" },
  workspaceKey: { type: "string", description: "Compatibility alias for workspace_key." },
  data: { type: "object" },
  evidence: { type: "object" },
  source: { type: "string", maxLength: 128 },
  confidence: { type: "string", maxLength: 128 },
  path: { type: "string" },
  before: { type: "object" },
  after: { type: "object" },
  frame_path: { type: "string" },
  script_hashes: { type: "array", items: { type: "string" } },
  storage_keys: { type: "array", items: { type: "string" } },
  user_agent: { type: "string" },
  active: { type: "boolean", default: false },
  focus_policy: {
    type: "string",
    enum: ["background_only", "background_preferred", "foreground"],
    default: "background_preferred",
    description: "foreground requires confirm_foreground=true and intentionally leaves the browser67-owned tab visible; background modes preserve the user's current workspace unless a bounded operation explicitly requires focus.",
  },
  confirm_foreground: { type: "boolean", default: false },
  confirm_managed_tab_overflow: { type: "boolean", default: false },
  window_policy: {
    type: "string",
    enum: ["dedicated", "current"],
    default: "dedicated",
    description: "current is schema-compatible but fails closed; exact user tabs require the browser_tab_lifecycle adoption flow.",
  },
  focus_lease_timeout_ms: { type: "number", minimum: 1000, maximum: 120000 },
  keep: { type: "boolean", default: false },
  fresh: { type: "boolean", default: false },
  reuse: { type: "boolean", default: true },
  ownership_policy: { type: "string", enum: ["tmwd_only", "fresh"], default: "tmwd_only" },
  reuse_scope: { type: "string", enum: ["exact", "origin_path", "origin", "none"], default: "origin_path" },
  reuse_key: { type: "string" },
  navigate_reused: { type: "boolean", default: true },
  scope: { type: "string", enum: ["workspace", "task", "all"] },
  all: { type: "boolean", default: false },
  confirm_all: { type: "boolean", default: false },
  prune_stale: { type: "boolean", default: false },
  cleanup_created_agent_window: {
    type: "boolean",
    default: false,
    description: "For finalize_task: retire only an exact Agent window created by this scoped task when it contains the sole anchor or a same browser-start epoch sole browser-generated New Tab after exact anchor removal or replacement; remove only exact internal tabs, follow bounded browser-generated New Tab successors, preserve concurrent user-content or unowned windows, and retain ownership if an internal successor remains unresolved.",
  },
  summary_only: { type: "boolean", default: false },
  dry_run: { type: "boolean", default: false },
  wait_timeout_ms: { type: "number", minimum: 0, maximum: 10000 },
  wait_poll_ms: { type: "number", minimum: 50, maximum: 1000 },
  tmwd_mode: { type: "string", enum: ["tmwd"] },
  tmwd_transport: { type: "string", enum: ["auto", "ws", "link"] },
  tmwd_ws_endpoint: { type: "string" },
  tmwd_link_endpoint: { type: "string" },
  timeout_ms: { type: "number", minimum: 500, maximum: 120000 },
};

const PAGE_TARGET_ARGUMENTS = [
  "browser_instance_id",
  "page_id",
  "session_id",
  "session_url_pattern",
  "tmwd_mode",
  "tmwd_transport",
  "tmwd_ws_endpoint",
  "tmwd_link_endpoint",
  "timeout_ms",
];
const SERVER_SCOPE_ARGUMENTS = ["workspace_key", "task_id"];
const FINALIZE_SCOPE_ARGUMENTS = [
  "workspace_key",
  "workspaceKey",
  "task_id",
  "taskId",
  "scope",
  "all",
  "confirm_all",
];

function argumentNames(...groups) {
  return [...new Set(groups.flat())];
}

const TOOL_ARGUMENTS = {
  check_browser_health: argumentNames(PAGE_TARGET_ARGUMENTS, ["summary_only"]),
  navigate_page: argumentNames(PAGE_TARGET_ARGUMENTS, ["url"]),
  new_page: argumentNames(PAGE_TARGET_ARGUMENTS, SERVER_SCOPE_ARGUMENTS, [
    "url", "active", "focus_policy", "confirm_foreground", "window_policy", "focus_lease_timeout_ms", "keep",
    "fresh", "reuse", "ownership_policy", "reuse_scope", "reuse_key", "navigate_reused",
    "confirm_managed_tab_overflow", "dry_run", "wait_timeout_ms", "wait_poll_ms",
  ]),
  finalize_task: argumentNames(PAGE_TARGET_ARGUMENTS, FINALIZE_SCOPE_ARGUMENTS, [
    "prune_stale", "cleanup_created_agent_window", "dry_run",
  ]),
  list_pages: PAGE_TARGET_ARGUMENTS,
  select_page: ["browser_instance_id", "page_id", "session_id"],
  list_scripts: PAGE_TARGET_ARGUMENTS,
  get_script_source: argumentNames(PAGE_TARGET_ARGUMENTS, ["script_id", "source_url"]),
  search_in_scripts: argumentNames(PAGE_TARGET_ARGUMENTS, ["keywords", "pattern", "script_limit", "max_records"]),
  find_in_script: argumentNames(PAGE_TARGET_ARGUMENTS, ["script_id", "source_url", "keywords", "pattern"]),
  list_network_requests: PAGE_TARGET_ARGUMENTS,
  get_network_request: argumentNames(PAGE_TARGET_ARGUMENTS, ["request_id"]),
  list_websocket_connections: PAGE_TARGET_ARGUMENTS,
  get_websocket_messages: PAGE_TARGET_ARGUMENTS,
  get_request_initiator: argumentNames(PAGE_TARGET_ARGUMENTS, ["request_id"]),
  get_dom_structure: PAGE_TARGET_ARGUMENTS,
  list_frames: argumentNames(PAGE_TARGET_ARGUMENTS, ["frame_path"]),
  detect_microfrontends: PAGE_TARGET_ARGUMENTS,
  create_hook: argumentNames(SERVER_SCOPE_ARGUMENTS, ["hook_id", "type", "target", "pattern"]),
  inject_hook: argumentNames(PAGE_TARGET_ARGUMENTS, SERVER_SCOPE_ARGUMENTS, ["hook_id", "type", "target", "pattern"]),
  get_hook_data: argumentNames(PAGE_TARGET_ARGUMENTS, ["hook_id", "view", "max_records"]),
  remove_hook: argumentNames(PAGE_TARGET_ARGUMENTS, SERVER_SCOPE_ARGUMENTS, ["hook_id"]),
  list_hooks: SERVER_SCOPE_ARGUMENTS,
  hook_function: argumentNames(PAGE_TARGET_ARGUMENTS, SERVER_SCOPE_ARGUMENTS, ["hook_id", "target", "pattern"]),
  unhook_function: argumentNames(PAGE_TARGET_ARGUMENTS, ["target", "pattern"]),
  monitor_events: argumentNames(PAGE_TARGET_ARGUMENTS, ["monitor_id", "events"]),
  stop_monitor: argumentNames(PAGE_TARGET_ARGUMENTS, ["monitor_id", "hook_id"]),
  trace_function: argumentNames(PAGE_TARGET_ARGUMENTS, SERVER_SCOPE_ARGUMENTS, ["hook_id", "target", "pattern"]),
  inject_preload_script: argumentNames(PAGE_TARGET_ARGUMENTS, ["code"]),
  set_breakpoint: argumentNames(PAGE_TARGET_ARGUMENTS, ["script_id", "target"]),
  set_breakpoint_on_text: argumentNames(PAGE_TARGET_ARGUMENTS, ["keywords", "pattern"]),
  resume: PAGE_TARGET_ARGUMENTS,
  pause: PAGE_TARGET_ARGUMENTS,
  step_over: PAGE_TARGET_ARGUMENTS,
  step_into: PAGE_TARGET_ARGUMENTS,
  step_out: PAGE_TARGET_ARGUMENTS,
  evaluate_on_callframe: argumentNames(PAGE_TARGET_ARGUMENTS, ["code"]),
  break_on_xhr: argumentNames(PAGE_TARGET_ARGUMENTS, SERVER_SCOPE_ARGUMENTS, ["pattern", "url"]),
  analyze_target: argumentNames(PAGE_TARGET_ARGUMENTS, ["keywords", "pattern", "script_limit", "max_records"]),
  understand_code: ["code"],
  deobfuscate_code: ["code"],
  detect_crypto: ["code"],
  summarize_code: ["code"],
  risk_panel: ["code", "data"],
  record_reverse_evidence: argumentNames(SERVER_SCOPE_ARGUMENTS, ["channel", "data", "evidence", "source", "confidence"]),
  export_session_report: SERVER_SCOPE_ARGUMENTS,
  export_evidence_bundle: argumentNames(SERVER_SCOPE_ARGUMENTS, ["url", "frame_path", "script_hashes", "storage_keys"]),
  export_rebuild_bundle: argumentNames(SERVER_SCOPE_ARGUMENTS, ["data"]),
  diff_env_requirements: ["data"],
  collect_code: argumentNames(PAGE_TARGET_ARGUMENTS, ["keywords", "pattern", "script_limit", "max_records"]),
  collection_diff: ["before", "after"],
  inject_stealth: PAGE_TARGET_ARGUMENTS,
  set_user_agent: argumentNames(PAGE_TARGET_ARGUMENTS, ["user_agent"]),
  save_session_state: argumentNames(PAGE_TARGET_ARGUMENTS, SERVER_SCOPE_ARGUMENTS),
  restore_session_state: argumentNames(PAGE_TARGET_ARGUMENTS, SERVER_SCOPE_ARGUMENTS, ["data", "path"]),
  get_storage: PAGE_TARGET_ARGUMENTS,
  get_local_storage: argumentNames(PAGE_TARGET_ARGUMENTS, ["key", "max_value_chars"]),
  get_session_storage: argumentNames(PAGE_TARGET_ARGUMENTS, ["key", "max_value_chars"]),
  search_storage: argumentNames(PAGE_TARGET_ARGUMENTS, ["pattern", "storage_area", "max_records", "max_value_chars", "include_values"]),
  watch_storage_changes: argumentNames(PAGE_TARGET_ARGUMENTS, ["watch_id", "storage_area"]),
};

const missingToolArgumentMaps = Object.keys(TOOL_DEFINITIONS)
  .filter((name) => !Object.hasOwn(TOOL_ARGUMENTS, name));
const unknownToolArgumentMaps = Object.keys(TOOL_ARGUMENTS)
  .filter((name) => !Object.hasOwn(TOOL_DEFINITIONS, name));
if (missingToolArgumentMaps.length > 0 || unknownToolArgumentMaps.length > 0) {
  throw new Error(`js-reverse tool schema map mismatch: missing=${missingToolArgumentMaps.join(",")} unknown=${unknownToolArgumentMaps.join(",")}`);
}

const TOOL_SCHEMAS = Object.fromEntries(
  Object.entries(TOOL_DEFINITIONS).map(([name, description]) => {
    const properties = Object.fromEntries(TOOL_ARGUMENTS[name].map((propertyName) => {
      const definition = PROPERTY_DEFINITIONS[propertyName];
      if (!definition) throw new Error(`js-reverse tool ${name} references unknown property ${propertyName}`);
      return [propertyName, definition];
    }));
    return [name, {
      description,
      inputSchema: {
        type: "object",
        properties,
        additionalProperties: false,
      },
    }];
  }),
);

export {
  TOOL_SCHEMAS,
  VERSION,
};
